var androidConfig = {
  "statusBarColor":-1,
  "navBackIcon": "static/checkedImageName.png",
  "navBackIconWidth": 25,
  "navBackIconHeight": 25,
  "navBackgroundColor": -1,
  "navTitle": "一键登录/注册",
  "navTitleColor": -16777216,
  "isHideNav": false,

  "logoIconName": "static/yidun_logo.png",
  "logoWidth": 70,
  "logoHeight": 70,
  "logoTopYOffset": 50,
  "logoBottomYOffset": 0,
  "logoXOffset": 0,
  "isHideLogo": false,

  "maskNumberColor": -16777216,
  "maskNumberSize": 15,
  "maskNumberDpSize": 0,
  "maskNumberTopYOffset": 150,
  "maskNumberBottomYOffset": 0,
  "maskNumberXOffset": 0,

  "sloganSize": 15,
  "sloganDpSize": 0,
  "sloganColor": -16777216,
  "sloganTopYOffset": 200,
  "sloganXOffset": 0,
  "sloganBottomYOffset":0,

  "loginBtnText": "同意协议并登录",
  "loginBtnTextSize": 15,
  "loginBtnTextDpSize": 15,
  "loginBtnTextColor": -1,
  "loginBtnWidth": 300,
  "loginBtnHeight": 45,
  "loginBtnTopYOffset": 250,
  "loginBtnBottomYOffset": 0,
  "loginBtnXOffset": 0,
  "loginBtnBackgroundRes":"static/launchImage.png",

  "privacyTextColor": -6710887,
  "privacyProtocolColor": -13480449,
  "privacySize": 12,
  "privacyDpSize": 12,
  "privacyTopYOffset": 0,
  "privacyBottomYOffset": 50,
  "privacyXOffset": 0,
  "privacyMarginRight": 1,
  "privacyState": true,
  "isHidePrivacySmh": false,
  "isHidePrivacyCheckBox": false,
  "isPrivacyTextGravityCenter": false,
  "checkBoxGravity": 48,
  "checkedImageName": "static/checkedImageName.png",
  "unCheckedImageName": "static/unCheckedImageName.png",
  "privacyTextStart": "登录即同意",
  "protocolText": "",
  "protocolLink": "",
  "protocol2Text": "",
  "protocol2Link": "",
  "privacyTextEnd": "",
  "protocolNavHeight": 0,
  "protocolNavTitleSize": 0,
  "protocolNavTitleDpSize": 0,
  "protocolNavBackIconWidth": 25,
  "protocolNavBackIconHeight": 25,

  "protocolNavTitle": "易盾一键登录SDK服务条款",
  "protocolNavBackIcon": "static/checkedImageName.png",
  "protocolNavColor": -1,

  "backgroundImage":"",
  "backgroundGif": "",
  "backgroundVideo": "",
  "backgroundVideoImage": "",

  "isLandscape": false,
  "isDialogMode": false,
  "dialogWidth": 300,
  "dialogHeight": 500,
  "dialogX": 0,
  "dialogY": 0,
  "isBottomDialog": false,
  "widgets": [
  {
      "viewId": "view_title",
      "type": "TextView",
      "top": 10,
    "left": 0,
      "right": 10,
      "width": 20,
      "height": 20,
      "text": "",
    "font": 16,
      "positionType": 1,
    "backgroundImgPath": "static/yidun_logo.png"
  },
      {
          "viewId": "view_tips",
          "type": "TextView",
          "left": 110,
          "top": 350,
          "right": 0,
          "bottom": 0,
          "width": 150,
          "height": 50,
          "clickable": false,
          "text": "-- 其他方式登录 --",
          "font": 16,
          "textColor": "#797894"
      },
  {
      "viewId": "wx_button",
      "type": "Button",
      "text": "",
      "left": 110,
      "top": 380,
      "right": 0,
      "bottom": 0,
      "width": 32,
      "height": 32,
      "clickable": true,
    "backgroundImgPath": "static/weixin.png"
  },
  {
      "viewId": "qq_button",
      "type": "Button",
      "text": "",
      "left": 162,
      "top": 380,
      "right": 0,
      "bottom": 0,
      "width": 32,
      "height": 32,
      "clickable": true,
    "backgroundImgPath": "static/qq.png"
  },
  {
      "viewId": "wb_button",
      "type": "Button",
      "text": "",
      "left": 214,
      "top": 380,
      "right": 0,
      "bottom": 0,
      "width": 32,
      "height": 32,
      "clickable": true,
    "backgroundImgPath": "static/weibo.png"
  }
  ]
}

var iosDarkConfig = {
  "presentDirectionType": "1",
  "backgroundColor": "#FFFFFF",
  "navBarHidden": false,
  "navBgColor": "#3478F7",
  "navText": "易盾登录",
  "navTextFont": 16,
  "navTextColor": "#ffffff",
  "navTextHidden": false,
  "navReturnImg": "static/back.jpg",
  "navReturnImgLeftMargin": 0,
  "navReturnImgBottomMargin": 0,
  "navReturnImgWidth": 60,
  "navReturnImgHeight": 60,
  "logoIconName": "static/checkedBox",
  "logoWidth": 50,
  "logoHeight": 50,
  "logoOffsetY": 0,
  "logoOffsetX": 0,
  "logoHidden": false,
  "logoOffsetTopY": 50,
  "numberColor": "#000000",
  "numberOffsetY": 10,
  "numberOffsetX": 0,
  "numberHeight": 50,
  "numberFont": 14,
  "numberCornerRadius": 10,
  "numberLeftContent": "",
  "numberRightContent": "",
  "numberOffsetTopY": "100",
  "brandColor": "#000000",
  "brandWidth": 100,
  "brandHeight": 20,
  "brandFont": 15,
  "brandOffsetY": 0,
  "brandOffsetX": 0,
  "brandHidden": false,
  "brandLogoOffsetMargin": 0,
  "brandLogoWidth": 50,
  "brandLogoHeight": 50,
  "brandOffsetTopY": 170,
  "logBtnText": "确定登录",
  "loginBtnTextSize": 15,
  "logBtnTextColor": "#000",
  "logBtnOffsetY": 0,
  "logBtnRadius": 20,
  "logBtnHeight": 40,
  "logBtnOriginLeft": 80,
  "logBtnOriginRight": 80,
  "logBtnUsableBGColor": "#0099FF",
  "logBtnOffsetTopY": 230,
  "logBtnEnableImg": "logo",
  "logBtnHighlightedImg": "pic_success",
  "checkedImageName": "static/checkedImageName.png",
  "unCheckedImageName": "static/unCheckedImageName.png",
  "checkboxWH": 50,
  "privacyState": true,
  "checkedHidden": true,
  "checkBoxAlignment": 0,
  "checkBoxMargin": 0,
  "appPrivacyOriginLeft": 40,
  "appPrivacyOriginRight": 40,
  "appPrivacyText": "登录即同意《默认》和《用户隐私协议》,《用户协议》",
  "appPrivacyTitleText": "中国移动认证服务条款",
  "appFPrivacyText": "用户隐私协议",
  "appFPrivacyTitleText": "用户隐私协议appFPrivacyTitleText",
  "appFPrivacyURL": "www.example.com",
  "appSPrivacyText": "用户协议",
  "appSPrivacyTitleText": "用户协议appSPrivacyTitleText",
  "appSPrivacyURL": "www.google.com",
  "appPrivacyAlignment": 0,
  "appPrivacyOriginLeftMargin": 60,
  "appPrivacyOriginBottomMargin": 60,
  "shouldHiddenPrivacyMarks": 0,
  "privacyNavReturnImg": "static/back.jpg",
  "privacyFont": 15,
  "privacyColor": "#000000",
  "protocolColor": "#3478F7",

  "authWindowPop": 0,
  "scaleW": 0.9,
  "scaleH": 0.5,
  "closePopImg": "back",
  "closePopImgWidth": 20,
  "closePopImgHeight": 20,
  "closePopImgOriginY": -10,
  "closePopImgOriginX": -10,
  "authWindowCenterOriginY": 0,
  "authWindowCenterOriginX": 0,
  "popCenterCornerRadius": 16,
  "popBottomCornerRadius": 10,
  "popBackgroundColor": "#0099FF",
  "alpha": 0.5,
  "isOpenSwipeGesture": true,

  "isRepeatPlay": "YES",
  "localVideoFileName": "video_portrait.mp4",
  "animationDuration": 2,
  "animationRepeatCount": 1000,

  "bgImage":"launchImage.png",
  "launchImage":"kj_pic_bg",
  "faceOrientation" : 1,
  "loginDidDisapperfaceOrientation" : 1,
  "modalTransitionStyle": 1,
  
  "currentStatusBarStyle": 0,
  "otherStatusBarStyle": 1,
  "customViewBlock":1,
  "widgets": [
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weixin.png",
			"title": "",	
			"titleColor": "#000000",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent1",
			"frame": {"mainScreenLeftDistance":100,"mainScreenTopDistance":360,"width":32,"height":32},
			"backgroundImage":"static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/qq.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent2",
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":360,"width":32,"height":32},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weibo.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent3",
			"frame": {"mainScreenRightDistance":100,"mainScreenTopDistance":360,"width":32,"height":32},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UILabel",
			"textColor": "#000000",
			"font": 15,
			"action": "handleCustomLabel",
			"text": "其他登录方式",
			"textAlignment": 1,
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":310,"width":200,"height":32}
		}
	]
}

var iosLightConfig = {
  "presentDirectionType": "1",
  "backgroundColor": "#FFFFFF",
  "navBarHidden": false,
  "navBgColor": "#3478F7",
  "navText": "易盾登录",
  "navTextFont": 16,
  "navTextColor": "#ffffff",
  "navTextHidden": false,
  "navReturnImg": "static/back.jpg",
  "navReturnImgLeftMargin": 0,
  "navReturnImgBottomMargin": 0,
  "navReturnImgWidth": 60,
  "navReturnImgHeight": 60,
  "logoIconName": "static/checkedBox",
  "logoWidth": 50,
  "logoHeight": 50,
  "logoOffsetX": 0,
  "logoHidden": false,
  "logoOffsetTopY": 50,
  "numberColor": "#000000",
  "numberOffsetX": 0,
  "numberHeight": 50,
  "numberFont": 14,
  "numberCornerRadius": 10,
  "numberLeftContent": "",
  "numberRightContent": "",
  "numberOffsetTopY": "100",
  "brandColor": "#000000",
  "brandWidth": 100,
  "brandHeight": 20,
  "brandFont": 15,
  "brandOffsetX": 0,
  "brandHidden": false,
  "brandLogoOffsetMargin": 0,
  "brandLogoWidth": 50,
  "brandLogoHeight": 50,
  "brandOffsetTopY": 170,
  "logBtnText": "确定登录",
  "loginBtnTextSize": 15,
  "logBtnTextColor": "#00FF99",
  "logBtnRadius": 20,
  "logBtnHeight": 40,
  "logBtnOriginLeft": 80,
  "logBtnOriginRight": 80,
  "logBtnUsableBGColor": "#0099FF",
  "logBtnOffsetTopY": 230,
  "logBtnEnableImg": "logo",
  "logBtnHighlightedImg": "pic_success",
  "checkedImageName": "static/checkedImageName.png",
  "unCheckedImageName": "static/unCheckedImageName.png",
  "checkboxWH": 50,
  "privacyState": true,
  "checkedHidden": true,
  "checkBoxAlignment": 0,
  "checkBoxMargin": 0,
  "appPrivacyOriginLeft": 40,
  "appPrivacyOriginRight": 40,
  "appPrivacyText": "登录即同意《默认》和《用户隐私协议》,《用户协议》",
  "appPrivacyTitleText": "中国移动认证服务条款",
  "appFPrivacyText": "用户隐私协议",
  "appFPrivacyTitleText": "用户隐私协议appFPrivacyTitleText",
  "appFPrivacyURL": "www.example.com",
  "appSPrivacyText": "用户协议",
  "appSPrivacyTitleText": "用户协议appSPrivacyTitleText",
  "appSPrivacyURL": "www.google.com",
  "appPrivacyAlignment": 0,
  "appPrivacyOriginLeftMargin": 60,
  "appPrivacyOriginBottomMargin": 60,
  "shouldHiddenPrivacyMarks": 0,
  "privacyNavReturnImg": "static/back.jpg",
  "privacyFont": 15,
  "privacyColor": "#000000",
  "protocolColor": "#3478F7",

  "authWindowPop": 0,
  "scaleW": 0.9,
  "scaleH": 0.5,
  "closePopImg": "back",
  "closePopImgWidth": 20,
  "closePopImgHeight": 20,
  "closePopImgOriginY": -10,
  "closePopImgOriginX": -10,
  "authWindowCenterOriginY": 0,
  "authWindowCenterOriginX": 0,
  "popCenterCornerRadius": 16,
  "popBottomCornerRadius": 10,
  "popBackgroundColor": "#0099FF",
  "alpha": 0.5,
  "isOpenSwipeGesture": true,

  "isRepeatPlay": "YES",
  "localVideoFileName": "video_portrait.mp4",
  "animationDuration": 2,
  "animationRepeatCount": 1000,

  "bgImage":"launchImage.png",
  "launchImage":"kj_pic_bg",
  "faceOrientation" : 1,
  "loginDidDisapperfaceOrientation" : 1,
  "modalTransitionStyle": 1,
  
  "statusBarStyle": 0,
  "widgets": [
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weixin.png",
			"title": "",	
			"titleColor": "#000000",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent1",
			"frame": {"mainScreenLeftDistance":70,"mainScreenTopDistance":340,"width":40,"height":40},
			"backgroundImage":"static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/qq.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent2",
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":340,"width":40,"height":40},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weibo.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent3",
			"frame": {"mainScreenRightDistance":70,"mainScreenTopDistance":340,"width":40,"height":40},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UILabel",
			"textColor": "#000000",
			"font": 15,
			"action": "handleCustomLabel",
			"text": "其他登录方式",
			"textAlignment": 1,
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":280,"width":200,"height":40}
		}
	]
}
