var androidConfig = {
  "statusBarColor": "#ffffff",
  "isStatusBarDarkColor": true,
  "logoIconName": "static/yidun_logo.png",
  "logoWidth": 200,
  "logoHeight": 70,
  "logoTopYOffset": 90,
  "maskNumberColor": "#000000",
  "maskNumberSize": 25,
  "maskNumberTopYOffset": 190,
  "sloganSize": 13,
  "sloganColor": "#9A9A9A",
  "sloganTopYOffset": 240,
  "loginBtnText": "易盾一键登录",
  "loginBtnTextColor": "#ffffff",
  "loginBtnWidth": 240,
  "loginBtnHeight": 45,
  "loginBtnTopYOffset": 280,
  "loginBtnBackgroundRes": "static/launchImage.png",
  "privacyTextColor": "#292929",
  "privacyProtocolColor": "#3F51B5",
  "privacySize": 13,
  "privacyBottomYOffset": 24,
  "privacyMarginLeft": 40,
  "privacyMarginRight": 40,
  "isPrivacyTextGravityCenter": false,
  "checkBoxGravity": 48,
  "privacyTextMarginLeft": 8,
  "checkBoxWith": 20,
  "checkBoxHeight": 20,
  "checkedImageName": "static/checkedImageName.png",
  "unCheckedImageName": "static/unCheckedImageName.png",
  "privacyTextStart": "我已阅读并同意",
  "protocolText": "用户协议",
  "privacyTextEnd": "",
  "isHidePrivacySmh": true,
  "protocolNavTitle": "易盾一键登录SDK服务条款",
  "protocolNavColor": "#FFFFFF",
  "isShowPrivacyDialog": false
}

var iosDarkConfig = {
  "presentDirectionType": "1",
  "backgroundColor": "#FFFFFF",
  "navBarHidden": false,
  "navBgColor": "#3478F7",
  "navText": "易盾登录",
  "navTextFont": 16,
  "navTextColor": "#ffffff",
  "navTextHidden": false,
  "navReturnImg": "static/back.jpg",
  "navReturnImgLeftMargin": 0,
  "navReturnImgBottomMargin": 0,
  "navReturnImgWidth": 60,
  "navReturnImgHeight": 60,
  "logoIconName": "static/checkedBox",
  "logoWidth": 50,
  "logoHeight": 50,
  "logoOffsetY": 0,
  "logoOffsetX": 0,
  "logoHidden": false,
  "logoOffsetTopY": 50,
  "numberColor": "#000000",
  "numberOffsetY": 10,
  "numberOffsetX": 0,
  "numberHeight": 50,
  "numberFont": 14,
  "numberCornerRadius": 10,
  "numberLeftContent": "",
  "numberRightContent": "",
  "numberOffsetTopY": "100",
  "brandColor": "#000000",
  "brandWidth": 100,
  "brandHeight": 20,
  "brandFont": 15,
  "brandOffsetY": 0,
  "brandOffsetX": 0,
  "brandHidden": false,
  "brandLogoOffsetMargin": 0,
  "brandLogoWidth": 50,
  "brandLogoHeight": 50,
  "brandOffsetTopY": 170,
  "logBtnText": "确定登录",
  "loginBtnTextSize": 15,
  "logBtnTextColor": "#000",
  "logBtnOffsetY": 0,
  "logBtnRadius": 20,
  "logBtnHeight": 40,
  "logBtnOriginLeft": 80,
  "logBtnOriginRight": 80,
  "logBtnUsableBGColor": "#0099FF",
  "logBtnOffsetTopY": 230,
  "logBtnEnableImg": "logo",
  "logBtnHighlightedImg": "pic_success",
  "checkedImageName": "static/checkedImageName.png",
  "unCheckedImageName": "static/unCheckedImageName.png",
  "checkboxWH": 50,
  "privacyState": true,
  "checkedHidden": true,
  "checkBoxAlignment": 0,
  "checkBoxMargin": 0,
  "appPrivacyOriginLeft": 40,
  "appPrivacyOriginRight": 40,
  "appPrivacyText": "登录即同意《默认》和《用户隐私协议》,《用户协议》",
  "appPrivacyTitleText": "中国移动认证服务条款",
  "appFPrivacyText": "用户隐私协议",
  "appFPrivacyTitleText": "用户隐私协议appFPrivacyTitleText",
  "appFPrivacyURL": "www.example.com",
  "appSPrivacyText": "用户协议",
  "appSPrivacyTitleText": "用户协议appSPrivacyTitleText",
  "appSPrivacyURL": "www.google.com",
  "appPrivacyAlignment": 0,
  "appPrivacyOriginLeftMargin": 60,
  "appPrivacyOriginBottomMargin": 60,
  "shouldHiddenPrivacyMarks": 0,
  "privacyNavReturnImg": "static/back.jpg",
  "privacyFont": 15,
  "privacyColor": "#000000",
  "protocolColor": "#3478F7",

  "authWindowPop": 0,
  "scaleW": 0.9,
  "scaleH": 0.5,
  "closePopImg": "back",
  "closePopImgWidth": 20,
  "closePopImgHeight": 20,
  "closePopImgOriginY": -10,
  "closePopImgOriginX": -10,
  "authWindowCenterOriginY": 0,
  "authWindowCenterOriginX": 0,
  "popCenterCornerRadius": 16,
  "popBottomCornerRadius": 10,
  "popBackgroundColor": "#0099FF",
  "alpha": 0.5,
  "isOpenSwipeGesture": true,

  "isRepeatPlay": "YES",
  "localVideoFileName": "video_portrait.mp4",
  "animationDuration": 2,
  "animationRepeatCount": 1000,

  "bgImage":"launchImage.png",
  "launchImage":"kj_pic_bg",
  "faceOrientation" : 1,
  "loginDidDisapperfaceOrientation" : 1,
  "modalTransitionStyle": 1,
  
  "currentStatusBarStyle": 0,
  "otherStatusBarStyle": 1,
  "customViewBlock":1,
  "widgets": [
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weixin.png",
			"title": "",	
			"titleColor": "#000000",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent1",
			"frame": {"mainScreenLeftDistance":100,"mainScreenTopDistance":360,"width":32,"height":32},
			"backgroundImage":"static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/qq.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent2",
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":360,"width":32,"height":32},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weibo.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent3",
			"frame": {"mainScreenRightDistance":100,"mainScreenTopDistance":360,"width":32,"height":32},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UILabel",
			"textColor": "#000000",
			"font": 15,
			"action": "handleCustomLabel",
			"text": "其他登录方式",
			"textAlignment": 1,
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":310,"width":200,"height":32}
		}
	]
}

var iosLightConfig = {
  "presentDirectionType": "1",
  "backgroundColor": "#FFFFFF",
  "navBarHidden": false,
  "navBgColor": "#3478F7",
  "navText": "易盾登录",
  "navTextFont": 16,
  "navTextColor": "#ffffff",
  "navTextHidden": false,
  "navReturnImg": "static/back.jpg",
  "navReturnImgLeftMargin": 0,
  "navReturnImgBottomMargin": 0,
  "navReturnImgWidth": 60,
  "navReturnImgHeight": 60,
  "logoIconName": "static/checkedBox",
  "logoWidth": 50,
  "logoHeight": 50,
  "logoOffsetX": 0,
  "logoHidden": false,
  "logoOffsetTopY": 50,
  "numberColor": "#000000",
  "numberOffsetX": 0,
  "numberHeight": 50,
  "numberFont": 14,
  "numberCornerRadius": 10,
  "numberLeftContent": "",
  "numberRightContent": "",
  "numberOffsetTopY": "100",
  "brandColor": "#000000",
  "brandWidth": 100,
  "brandHeight": 20,
  "brandFont": 15,
  "brandOffsetX": 0,
  "brandHidden": false,
  "brandLogoOffsetMargin": 0,
  "brandLogoWidth": 50,
  "brandLogoHeight": 50,
  "brandOffsetTopY": 170,
  "logBtnText": "确定登录",
  "loginBtnTextSize": 15,
  "logBtnTextColor": "#00FF99",
  "logBtnRadius": 20,
  "logBtnHeight": 40,
  "logBtnOriginLeft": 80,
  "logBtnOriginRight": 80,
  "logBtnUsableBGColor": "#0099FF",
  "logBtnOffsetTopY": 230,
  "logBtnEnableImg": "logo",
  "logBtnHighlightedImg": "pic_success",
  "checkedImageName": "static/checkedImageName.png",
  "unCheckedImageName": "static/unCheckedImageName.png",
  "checkboxWH": 50,
  "privacyState": true,
  "checkedHidden": true,
  "checkBoxAlignment": 0,
  "checkBoxMargin": 0,
  "appPrivacyOriginLeft": 40,
  "appPrivacyOriginRight": 40,
  "appPrivacyText": "登录即同意《默认》和《用户隐私协议》,《用户协议》",
  "appPrivacyTitleText": "中国移动认证服务条款",
  "appFPrivacyText": "用户隐私协议",
  "appFPrivacyTitleText": "用户隐私协议appFPrivacyTitleText",
  "appFPrivacyURL": "www.example.com",
  "appSPrivacyText": "用户协议",
  "appSPrivacyTitleText": "用户协议appSPrivacyTitleText",
  "appSPrivacyURL": "www.google.com",
  "appPrivacyAlignment": 0,
  "appPrivacyOriginLeftMargin": 60,
  "appPrivacyOriginBottomMargin": 60,
  "shouldHiddenPrivacyMarks": 0,
  "privacyNavReturnImg": "static/back.jpg",
  "privacyFont": 15,
  "privacyColor": "#000000",
  "protocolColor": "#3478F7",

  "authWindowPop": 0,
  "scaleW": 0.9,
  "scaleH": 0.5,
  "closePopImg": "back",
  "closePopImgWidth": 20,
  "closePopImgHeight": 20,
  "closePopImgOriginY": -10,
  "closePopImgOriginX": -10,
  "authWindowCenterOriginY": 0,
  "authWindowCenterOriginX": 0,
  "popCenterCornerRadius": 16,
  "popBottomCornerRadius": 10,
  "popBackgroundColor": "#0099FF",
  "alpha": 0.5,
  "isOpenSwipeGesture": true,

  "isRepeatPlay": "YES",
  "localVideoFileName": "video_portrait.mp4",
  "animationDuration": 2,
  "animationRepeatCount": 1000,

  "bgImage":"launchImage.png",
  "launchImage":"kj_pic_bg",
  "faceOrientation" : 1,
  "loginDidDisapperfaceOrientation" : 1,
  "modalTransitionStyle": 1,
  
  "statusBarStyle": 0,
  "widgets": [
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weixin.png",
			"title": "",	
			"titleColor": "#000000",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent1",
			"frame": {"mainScreenLeftDistance":70,"mainScreenTopDistance":340,"width":40,"height":40},
			"backgroundImage":"static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/qq.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent2",
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":340,"width":40,"height":40},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UIButton", 
			"UIButtonType": 0, 
			"image": "static/weibo.png",
			"title": "",	
			"titleColor": "#FFFFFF",
			"titleFont": 12,
			"cornerRadius": 20,
			"action": "handleCustomEvent3",
			"frame": {"mainScreenRightDistance":70,"mainScreenTopDistance":340,"width":40,"height":40},
			"backgroundImage": "static/yidun_logo.png"
		},
		{
			"type": "UILabel",
			"textColor": "#000000",
			"font": 15,
			"action": "handleCustomLabel",
			"text": "其他登录方式",
			"textAlignment": 1,
			"frame": {"mainScreenCenterXWithLeftDistance":0,"mainScreenTopDistance":280,"width":200,"height":40}
		}
	]
}
